version: "3.7"
services:
  redis:
    image: bitnami/redis:5.0
    container_name: redis
    command: redis-server --requirepass redis_pw --save ''
    restart: unless-stopped
    environment:
      - REDIS_AOF_ENABLED=no
    ports:
      - "6379:6379"